# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-things
spec:
  replicas: {{ .Values.defaults.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: things
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "{{ .Values.things.httpPort }}"
        prometheus.io/scrape: "true"
      labels:
        app: {{ .Release.Name }}
        component: things
    spec:
      {{- with (default .Values.defaults.image.pullSecrets .Values.things.image.pullSecrets) }}
      imagePullSecrets:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
        - name: {{ .Release.Name }}-things
          image: "{{ default (printf "%s/things" .Values.defaults.image.rootRepository) .Values.things.image.repository }}:{{ default .Values.defaults.image.tag .Values.things.image.tag }}"
          imagePullPolicy: {{ default .Values.defaults.image.pullPolicy .Values.things.image.pullPolicy }}
          env:
            - name: SMQ_JAEGER_URL
              value: "http://{{ .Release.Name }}-jaeger-collector:{{ .Values.defaults.jaegerCollectorPort }}/v1/traces"
            - name: SMQ_THINGS_AUTH_GRPC_HOST
              value: "0.0.0.0"
            - name: SMQ_THINGS_AUTH_GRPC_PORT
              value: {{ .Values.things.authGrpcPort | quote}}
            - name: SMQ_THINGS_AUTH_HTTP_HOST
              value: "0.0.0.0"
            - name: SMQ_THINGS_AUTH_HTTP_PORT
              value: {{ .Values.things.authHttpPort | quote}}
            - name: SMQ_THINGS_CACHE_URL
              value: redis://{{ .Release.Name }}-redis-things-master:{{ .Values.things.redisCachePort }}/0
            - name: SMQ_THINGS_DB_HOST
            {{- if .Values.postgresqlthings.enabled }}
              value: {{ .Release.Name }}-postgresqlthings
            {{- else }}
              value: {{ .Values.postgresqlthings.host | quote}}
            {{- end }}
            - name: SMQ_THINGS_DB_PORT
              value: {{ .Values.postgresqlthings.port | quote}}
            - name: SMQ_THINGS_DB_USER
              value: {{ .Values.postgresqlthings.username | quote }}
            - name: SMQ_THINGS_DB_PASS
              value: {{ .Values.postgresqlthings.password | quote }}
            - name: SMQ_THINGS_DB_NAME
              value: {{ .Values.postgresqlthings.database | quote }}
            - name: SMQ_ES_URL
              value: {{ .Values.defaults.eventStreamURL | quote }}
            - name: SMQ_THINGS_HTTP_HOST
              value: "0.0.0.0"
            - name: SMQ_THINGS_HTTP_PORT
              value: {{ .Values.things.httpPort | quote }}
            - name: SMQ_THINGS_LOG_LEVEL
              value: {{ default .Values.defaults.logLevel .Values.things.logLevel | quote }}
            - name: SMQ_AUTH_GRPC_URL
              value: {{ .Release.Name }}-envoy:{{ .Values.auth.grpcPort }}
          ports:
            - containerPort: {{ .Values.things.httpPort }}
              protocol: TCP
            - containerPort: {{ .Values.things.authGrpcPort }}
              protocol: TCP
            - containerPort: {{ .Values.things.authHttpPort }}
              protocol: TCP
      {{- with .Values.things.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.things.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.things.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
