# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-journal
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: journal
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "{{ .Values.journal.httpPort }}"
        prometheus.io/scrape: "true"
      labels:
        app: {{ .Release.Name }}
        component: journal
    spec:
      {{- with (default .Values.defaults.image.pullSecrets .Values.journal.image.pullSecrets) }}
      imagePullSecrets:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
        - name: {{ .Release.Name }}-journal
          image: "{{ default (printf "%s/journal" .Values.defaults.image.rootRepository) .Values.journal.image.repository }}:{{ default .Values.defaults.image.tag .Values.journal.image.tag }}"
          imagePullPolicy: {{ default .Values.defaults.image.pullPolicy .Values.journal.image.pullPolicy }}
          env:
            - name: SMQ_JAEGER_URL
              value: "http://{{ .Values.jaeger.fullnameOverride }}-collector:{{ .Values.jaeger.collector.service.otlp.http.port }}/v1/traces"
            - name: SMQ_JAEGER_TRACE_RATIO
              value: {{ default .Values.defaults.jaegerTraceRatio .Values.journal.jaegerTraceRatio | quote  }}
            - name: SMQ_SEND_TELEMETRY
              value: {{ default .Values.defaults.sendTelemetry .Values.journal.sendTelemetry | quote  }}
            - name: SMQ_ES_URL
              value: {{ .Values.defaults.eventStreamURL | quote }}
            - name: SMQ_JOURNAL_LOG_LEVEL
              value: {{ default .Values.defaults.logLevel .Values.journal.logLevel  | quote }}
            - name: SMQ_JOURNAL_HTTP_HOST
              value: "0.0.0.0"
            - name: SMQ_JOURNAL_HTTP_PORT
              value: {{ .Values.journal.httpPort  | quote  }}
            - name : SMQ_AUTH_GRPC_URL
              value: {{ .Release.Name }}-envoy:{{ .Values.auth.grpcPort }}
            - name: SMQ_JOURNAL_DB_HOST
            {{- if .Values.postgresqljournal.enabled }}
              value: "{{ .Release.Name }}-postgresqljournal"
            {{- else }}
              value: {{ .Values.postgresqljournal.host | quote }}
            {{- end }}
            - name: SMQ_JOURNAL_DB_PORT
              value: {{ .Values.postgresqljournal.port  | quote }}
            - name: SMQ_JOURNAL_DB_NAME
              value: {{ .Values.postgresqljournal.database | quote }}
            - name: SMQ_JOURNAL_DB_USER
              value: {{ .Values.postgresqljournal.username | quote }}
            - name: SMQ_JOURNAL_DB_PASS
              value: {{ .Values.postgresqljournal.password | quote }}
          ports:
            - containerPort: {{ .Values.journal.httpPort }}
              protocol: TCP
      {{- with .Values.journal.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.journal.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.journal.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
