# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.adapter_opcua.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-adapter-opcua
spec:
  selector:
    app: {{ .Release.Name }}
    component: adapter-opcua
  ports:
    - port: {{ .Values.adapter_opcua.httpPort }}
      protocol: TCP
{{- end }}
