# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.adapter_opcua.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-adapter-opcua
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: adapter-opcua
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "{{ .Values.adapter_opcua.httpPort }}"
        prometheus.io/scrape: "true"
      labels:
        app: {{ .Release.Name }}
        component: adapter-opcua
    spec:
      containers:
        - env:
            - name: MG_OPCUA_ADAPTER_HTTP_PORT
              value: "{{ .Values.adapter_opcua.httpPort }}"
            - name: MG_OPCUA_ADAPTER_LOG_LEVEL
              value: {{ default .Values.defaults.logLevel .Values.adapter_opcua.logLevel }}
            - name: MG_BROKER_URL
              value: nats://{{ .Release.Name }}-nats-client:{{ .Values.defaults.natsPort }}
            - name: MG_OPCUA_ADAPTER_POLICY
              value: {{ .Values.adapter_opcua.policy }}
            - name: MG_OPCUA_ADAPTER_MODE
              value: {{ .Values.adapter_opcua.mode }}
            - name: MG_OPCUA_ADAPTER_CERT_FILE
              value: {{ .Values.adapter_opcua.certFile }}
            - name: MG_OPCUA_ADAPTER_KEY_FILE
              value: {{ .Values.adapter_opcua.keyFile }}
            - name: MG_OPCUA_ADAPTER_ROUTE_MAP_URL
              value: {{ .Release.Name }}-redis-opcua-master:{{ .Values.adapter_opcua.redisRouteMapPort }}
            - name: MG_THINGS_ES_URL
              value: {{ .Release.Name }}-redis-streams-master:{{ .Values.things.redisESPort }}
            - name: MG_OPCUA_ADAPTER_EVENT_CONSUMER
              value: {{ .Values.adapter_opcua.eventConsumer }}
          image: "{{ default .Values.defaults.image.repository .Values.adapter_opcua.image.repository }}/opcua:{{ default .Values.defaults.image.tag .Values.adapter_opcua.image.tag }}"
          imagePullPolicy: {{ default .Values.defaults.image.pullPolicy .Values.adapter_opcua.image.pullPolicy }}
          name: {{ .Release.Name }}-adapter-opcua
          ports:
            - containerPort: {{ .Values.adapter_opcua.httpPort }}
              protocol: TCP
          stdin: true
          tty: true
      {{- with .Values.defaults.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
{{- end }}
