# Copyright (c) Mainflux
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-authn
spec:
  selector:
    app: {{ .Release.Name }}
    component: authn
  ports:
    - protocol: TCP
      port: {{ .Values.authn.httpPort }}
      name: {{ .Release.Name }}-authn-http
    - protocol: TCP
      port: {{ .Values.authn.grpcPort }
      name: {{ .Release.Name }}-authn-grpc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-authn-headless
spec:
  selector:
    app: {{ .Release.Name }}
    component: authn
  ports:
    - protocol: TCP
      port: {{ .Values.authn.httpPort }}
      name: {{ .Release.Name }}-authn-http
    - protocol: TCP
      port: {{ .Values.authn.grpcPort }
      name: {{ .Release.Name }}-authn-grpc
  clusterIP: None
