# Copyright (c) Mainflux
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-auth
spec:
  replicas: {{ .Values.defaults.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: auth
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "{{ .Values.auth.httpPort }}"
        prometheus.io/scrape: "true"
      labels:
        app: {{ .Release.Name }}
        component: auth
    spec:
      containers:
        - env:
            - name: MG_JAEGER_URL
              value: {{ .Release.Name }}-jaeger-operator-jaeger-agent:{{ .Values.defaults.jaegerPort }}
            - name: MG_AUTH_DB
              value: {{ .Values.postgresqlauth.postgresqlDatabase | quote }}
            - name: MG_AUTH_DB_HOST
            {{- if .Values.postgresqlauth.enabled }}
              value: {{ .Release.Name }}-postgresqlauth
            {{- else }}
              value: {{ .Values.postgresqlauth.postgresqlHost | quote }}
            {{- end }}
            - name: MG_AUTH_DB_PASS
              value: {{ .Values.postgresqlauth.postgresqlPassword | quote }}
            - name: MG_AUTH_DB_PORT
              value: "{{ .Values.auth.dbPort }}"
            - name: MG_AUTH_DB_USER
              value: {{ .Values.postgresqlauth.postgresqlUsername | quote }}
            - name: MG_AUTH_GRPC_PORT
              value: "{{ .Values.auth.grpcPort }}"
            - name: MG_AUTH_HTTP_PORT
              value: "{{ .Values.auth.httpPort }}"
            - name: MG_AUTH_LOG_LEVEL
              value: {{ default .Values.defaults.logLevel .Values.users.logLevel }}
            - name: MG_AUTH_SECRET
              value: "{{ .Values.auth.secret }}"
            - name: MG_KETO_WRITE_REMOTE_HOST
              value: {{ .Release.Name }}-keto-write
            - name: MG_KETO_READ_REMOTE_HOST
              value: {{ .Release.Name }}-keto-read              
            - name: MG_KETO_READ_REMOTE_PORT
              value: "{{ .Values.keto.service.read.port }}"
            - name: MG_KETO_WRITE_REMOTE_PORT
              value: "{{ .Values.keto.service.write.port }}"            
          image: "{{ default .Values.defaults.image.repository .Values.auth.image.repository }}/auth:{{ default .Values.defaults.image.tag .Values.auth.image.tag }}"
          imagePullPolicy: {{ default .Values.defaults.image.pullPolicy .Values.users.image.pullPolicy }}
          name: {{ .Release.Name }}-auth
          ports:
            - containerPort: {{ .Values.auth.httpPort }}
              protocol: TCP
            - containerPort: {{ .Values.auth.grpcPort }}
              protocol: TCP
      {{- with .Values.defaults.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
