Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.certs.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-certs
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: certs
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "{{ .Values.certs.httpPort }}"
        prometheus.io/scrape: "true"
      labels:
        app: {{ .Release.Name }}
        component: certs
    spec:
      containers:
        - env:
            - name: MG_CERTS_LOG_LEVEL
              value: {{ default .Values.defaults.logLevel .Values.certs.logLevel }}
            - name: MG_JAEGER_URL
              value: "http://{{ .Release.Name }}-jaeger-collector:{{ .Values.defaults.jaegerCollectorPort }}/api/traces"
            - name: MG_CERTS_DB_HOST
            {{- if .Values.postgresqlcerts.enabled }}
              value: {{ .Release.Name }}-postgresqlcerts
            {{- else }}
              value: {{ .Values.postgresqlcerts.postgresqlHost | quote }}
            {{- end }}
            - name: MG_CERTS_DB
              value: {{ index .Values  "postgresqlcerts" "auth" "database" }}
            - name: MG_CERTS_DB_PASS
              value: {{ index .Values  "postgresqlcerts" "auth" "password" }}
            - name: MG_CERTS_DB_PORT
              value: {{ .Values.postgresqlcerts.postgresqlPort | quote }}
            - name: MG_CERTS_DB_USER
              value: {{ index .Values  "postgresqlcerts" "auth" "username" }}
            - name: MG_CERTS_DB_SSL_MODE
              value: disable
            - name: MG_CERTS_DB_SSL_CERT
              value: disable
            - name: MG_CERTS_DB_SSL_KEY
              value: disable
            - name: MG_CERTS_DB_SSL_ROOT_CERT
              value: disable
            - name: MG_CERTS_ENCRYPT_KEY
              value: {{ index .Values "certs" "encryptKey" }}
            - name: MG_CERTS_CLIENT_TLS
              value: {{ index .Values "certs" "clientTLS" }}
            - name: MG_CERTS_SERVER_CERT
              value: {{ index .Values "certs" "serverCert" }}
            - name: MG_CERTS_SERVER_KEY
              value: {{ index .Values "certs" "serverKey" }}
            - name: MG_CERTS_HTTP_PORT
              value: "{{ .Values.certs.httpPort }}"
            - name: MG_AUTH_GRPC_URL
              value: {{ .Release.Name }}-envoy:{{ .Values.users.grpcPort }}
            - name: MG_THINGS_URL
              value: http://{{ .Release.Name }}-things:{{ .Values.things.httpPort }}
            - name: MG_SDK_THINGS_PREFIX
              value: {{ index .Values "certs" "sdkThingsPrefix" }}
            - name: MG_CERTS_SIGN_CA_PATH
              value: {{ index .Values "certs" "signCAPath" }}
            - name: MG_CERTS_SIGN_CA_KEY_PATH
              value: {{ index .Values "certs" "signCAKeyPath" }}
            - name: MG_CERTS_SIGN_HOURS_VALID
              value: {{ index .Values "certs" "signHoursValid" }}
            - name: MG_CERTS_SIGN_RSA_BITS
              value: "{{ .Values.certs.signRSABits }}"
            - name: MG_VAULT_TOKEN
              value: {{ index .Values "certs" "signVaultToken" }}
            - name: MG_CERTS_VAULT_HOST
              value: {{ index .Values "certs" "signVaultHost" }}
            - name: MG_VAULT_PKI_PATH
              value: {{ index .Values "certs" "signVaultPKIPath" }}
            - name: MG_VAULT_ROLE
              value: {{ index .Values "certs" "signVaultRole" }}
          image: "{{ default .Values.defaults.image.repository .Values.certs.image.repository }}/certs:{{ default .Values.defaults.image.tag .Values.certs.image.tag }}"
          imagePullPolicy: {{ default .Values.defaults.image.pullPolicy .Values.certs.image.pullPolicy }}
          name: {{ .Release.Name }}-certs
          ports:
            - containerPort: {{ .Values.certs.httpPort }}
              protocol: TCP
      {{- with .Values.defaults.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
{{- end }}
