# Copyright (c) Mainflux
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
data:
  envoy.yaml: |-
    static_resources:
      listeners:
      - address:
          socket_address:
            address: 0.0.0.0
            port_value: 1883
        filter_chains:
        - filters:
          - name: envoy.tcp_proxy
            config:
              stat_prefix: adapter-mqtt
              cluster: adapter-mqtt
      - address:
          socket_address:
            address: 0.0.0.0
            port_value: 8181
        filter_chains:
        - filters:
          - name: envoy.http_connection_manager
            config:
              codec_type: auto
              stat_prefix: authn
              route_config:
                name: authn_route
                virtual_hosts:
                - name: authn_service
                  domains: ["*"]
                  routes:
                  - match: { prefix: "/" }
                    route: { cluster: authn }
              http_filters:
              - name: envoy.grpc_web
              - name: envoy.router
      - address:
          socket_address:
            address: 0.0.0.0
            port_value: 8183
        filter_chains:
        - filters:
          - name: envoy.http_connection_manager
            config:
              codec_type: auto
              stat_prefix: things
              route_config:
                name: things_route
                virtual_hosts:
                - name: things_service
                  domains: ["*"]
                  routes:
                  - match: { prefix: "/" }
                    route: { cluster: things }
              http_filters:
              - name: envoy.grpc_web
              - name: envoy.router
      clusters:
      - name: adapter-mqtt
        connect_timeout: 0.25s
        type: strict_dns
        lb_policy: round_robin
        hosts:
        - socket_address:
            address: {{ .Release.Name }}-adapter-mqtt
            port_value: 1883
      - name: authn
        connect_timeout: 0.25s
        type: strict_dns
        lb_policy: round_robin
        http2_protocol_options: {}
        hosts:
        - socket_address:
            address: {{ .Release.Name }}-authn-headless
            port_value: 8181
      - name: things
        connect_timeout: 0.25s
        type: strict_dns
        lb_policy: round_robin
        http2_protocol_options: {}
        hosts:
        - socket_address:
            address: {{ .Release.Name }}-things-headless
            port_value: 8183            
    admin:
      access_log_path: "/dev/null"
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8001

kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-envoy-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-envoy
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: envoy
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: envoy
    spec:
      containers:
        - image: envoyproxy/envoy:v1.13.0
          imagePullPolicy: Always
          name: {{ .Release.Name }}-envoy
          ports:
            - containerPort: 1883 
              protocol: TCP
            - containerPort: 8181 
              protocol: TCP
            - containerPort: 8183 
              protocol: TCP
            - containerPort: 8001
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/envoy/envoy.yaml
              name: envoy-config
              subPath: envoy.yaml
      volumes:
        - configMap:
            defaultMode: 256
            name: {{ .Release.Name }}-envoy-config
            optional: false
          name: envoy-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-envoy
spec:
  selector:
    app: {{ .Release.Name }}
    component: envoy
  ports:
    - port: 1883
      protocol: TCP
      name: mqtt
    - port: 8181
      protocol: TCP
      name: authn-grpc
    - port: 8183
      protocol: TCP
      name: things-grpc
    - port: 8001
      protocol: TCP
      name: admin
  type: LoadBalancer
