# Copyright (c) Mainflux
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
data:
  envoy.yaml: |-
    static_resources:
      listeners:
      - address:
          socket_address:
            address: 0.0.0.0
            port_value: 1883
        filter_chains:
        - filters:
          - name: envoy.tcp_proxy
            config:
              stat_prefix: mqtt
              cluster: adapter-mqtt
      - address:
          socket_address:
            address: 0.0.0.0
            port_value: {{ .Values.auth.grpcPort }}
        filter_chains:
        - filters:
          - name: envoy.http_connection_manager
            config:
              codec_type: auto
              stat_prefix: auth
              route_config:
                name: auth_route
                virtual_hosts:
                - name: auth_service
                  domains: ["*"]
                  routes:
                  - match: { prefix: "/" }
                    route: { cluster: auth }
              http_filters:
              - name: envoy.grpc_web
              - name: envoy.router
      - address:
          socket_address:
            address: 0.0.0.0
            port_value: {{ .Values.things.authGrpcPort }}
        filter_chains:
        - filters:
          - name: envoy.http_connection_manager
            config:
              codec_type: auto
              stat_prefix: things
              route_config:
                name: things_route
                virtual_hosts:
                - name: things_service
                  domains: ["*"]
                  routes:
                  - match: { prefix: "/" }
                    route: { cluster: things }
              http_filters:
              - name: envoy.grpc_web
              - name: envoy.router
      clusters:
      - name: mqtt
        connect_timeout: 0.25s
        type: strict_dns
        lb_policy: round_robin
        hosts:
        - socket_address:
            address: {{ .Release.Name }}-mqtt
            port_value: 1884
      - name: auth
        connect_timeout: 0.25s
        type: strict_dns
        lb_policy: round_robin
        http2_protocol_options: {}
        hosts:
        - socket_address:
            address: {{ .Release.Name }}-auth-headless
            port_value: {{ .Values.auth.grpcPort }}
      - name: things
        connect_timeout: 0.25s
        type: strict_dns
        lb_policy: round_robin
        http2_protocol_options: {}
        hosts:
        - socket_address:
            address: {{ .Release.Name }}-things-headless
            port_value: {{ .Values.things.authGrpcPort }}
    admin:
      access_log_path: "/dev/null"
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8001

kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-envoy-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-envoy
spec:
  replicas: {{ .Values.defaults.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: envoy
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: envoy
    spec:
      containers:
        - image: "{{ default .Values.defaults.image.repository .Values.envoy.image.repository }}:{{ default .Values.defaults.image.tag .Values.envoy.image.tag }}"
          imagePullPolicy: {{ default .Values.defaults.image.pullPolicy .Values.envoy.image.imagePullPolicy}}
          name: {{ .Release.Name }}-envoy
          ports:
            - containerPort: 1883
              protocol: TCP
            - containerPort: {{ .Values.auth.grpcPort }}
              protocol: TCP
            - containerPort: {{ .Values.things.authGrpcPort }}
              protocol: TCP
            - containerPort: 8001
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/envoy/envoy.yaml
              name: envoy-config
              subPath: envoy.yaml
      volumes:
        - configMap:
            defaultMode: 256
            name: {{ .Release.Name }}-envoy-config
            optional: false
          name: envoy-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-envoy
spec:
  selector:
    app: {{ .Release.Name }}
    component: envoy
  ports:
    - port: 1883
      protocol: TCP
      name: mqtt
    - port: {{ .Values.auth.grpcPort }}
      protocol: TCP
      name: auth-grpc
    - port: {{ .Values.things.authGrpcPort }}
      protocol: TCP
      name: things-grpc
    - port: 8001
      protocol: TCP
      name: admin
