# Copyright (c) Mainflux
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-influxdb-reader
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: influxdb-reader
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: influxdb-reader
    spec:
      containers:
        - env:
            - name: MF_INFLUX_READER_LOG_LEVEL
              value: debug
            - name: MF_THINGS_AUTH_GRPC_URL
              value: {{ .Release.Name }}-envoy:8183
            - name: MF_INFLUX_READER_PORT
              value: "8905"                         
            - name: MF_INFLUX_READER_DB
              value: mainflux
            - name: MF_INFLUX_READER_DB_USER
              value: mainflux
            - name: MF_INFLUX_READER_DB_PASS
              value: mainflux              
            - name: MF_INFLUX_READER_DB_HOST
              value: {{ .Release.Name }}-influxdb
            - name: MF_INFLUX_READER_DB_PORT
              value: "8086"
            - name: MF_JAEGER_URL
              value: {{ .Release.Name }}-jaeger-operator-jaeger-agent:6831
          image: "{{ default .Values.defaults.image.repository .Values.influxdb_reader.image.repository }}/influxdb-reader:{{ default .Values.defaults.image.tag .Values.influxdb_reader.image.tag }}"
          imagePullPolicy: {{ default .Values.defaults.image.pullPolicy .Values.influxdb_reader.image.pullPolicy }}
          name: {{ .Release.Name }}-influxdb-reader
          ports:
            - containerPort: 8905
              protocol: TCP
          stdin: true
          tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
