# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.influxdb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-influxdb-writer
spec:
  selector:
    app: {{ .Release.Name }}
    component: influxdb-writer
  ports:
    - port: {{ .Values.influxdb.writer.httpPort }}
      protocol: TCP
      name: {{ .Release.Name }}-influxdb-writer-{{ .Values.influxdb.writer.httpPort }}
{{- end }}
