# Copyright (c) Mainflux
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.influxdb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-influxdb-reader
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: influxdb-reader
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: influxdb-reader
    spec:
      containers:
        - env:
            - name: MF_INFLUX_READER_LOG_LEVEL
              value: debug
            - name: MF_THINGS_AUTH_GRPC_URL
              value: {{ .Release.Name }}-envoy:{{ .Values.things.authGrpcPort }}
            - name: MF_INFLUX_READER_PORT
              value: "{{ .Values.influxdb.reader.httpPort }}"
            - name: MF_INFLUXDB_DB
              value: "{{ .Values.influxdb.database }}"
            - name: MF_INFLUXDB_ADMIN_USER
              value: "{{ .Values.influxdb.adminUser.name }}"
            - name: MF_INFLUXDB_ADMIN_PASSWORD
              value: "{{ .Values.influxdb.adminUser.pwd }}"
            - name: MF_INFLUXDB_HOST
              value: {{ .Release.Name }}-influxdb
            - name: MF_INFLUXDB_PORT
              value: "{{ .Values.influxdb.dbPort }}"
            - name: MF_JAEGER_URL
              value: {{ .Release.Name }}-jaeger-operator-jaeger-agent:{{ .Values.defaults.jaegerPort }}
          image: "{{ default .Values.defaults.image.repository .Values.influxdb.reader.image.repository }}/influxdb-reader:{{ default .Values.defaults.image.tag .Values.influxdb.reader.image.tag }}"
          imagePullPolicy: {{ default .Values.defaults.image.pullPolicy .Values.influxdb.reader.image.pullPolicy }}
          name: {{ .Release.Name }}-influxdb-reader
          ports:
            - containerPort: {{ .Values.influxdb.reader.httpPort }}
              protocol: TCP
          stdin: true
          tty: true
      {{- with .Values.defaults.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
{{- end }}
