# Copyright (c) Mainflux
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.mongodb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongdb-reader
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: mongodb-reader
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: mongodb-reader
    spec:
      containers:
        - env:
            - name: MF_MONGO_READER_LOG_LEVEL
              value: debug
            - name: MF_THINGS_AUTH_GRPC_URL
              value: {{ .Release.Name }}-envoy:{{ .Values.things.authGrpcPort }}
            - name: MF_MONGO_READER_PORT
              value: "{{ .Values.mongodb.reader.httpPort }}"
            - name: MF_MONGO_READER_DB
              value: "{{ .Values.mongodb.database }}"
            - name: MF_MONGO_READER_DB_USER
              value: "{{ .Values.mongodb.adminUser.name }}"
            - name: MF_MONGO_READER_DB_PASS
              value: "{{ .Values.mongodb.adminUser.pwd }}"
            - name: MF_MONGO_READER_DB_HOST
              value: {{ .Release.Name }}-mongodb
            - name: MF_MONGO_READER_DB_PORT
              value: "{{ .Values.mongodb.dbPort }}"
            - name: MF_JAEGER_URL
              value: {{ .Release.Name }}-jaeger-operator-jaeger-agent:{{ .Values.defaults.jaegerPort }}
          image: "{{ default .Values.defaults.image.repository .Values.mongodb.reader.image.repository }}/mongodb-reader:{{ default .Values.defaults.image.tag .Values.mongodb.reader.image.tag }}"
          imagePullPolicy: {{ default .Values.defaults.image.pullPolicy .Values.mongodb.reader.image.pullPolicy }}
          name: {{ .Release.Name }}-mongodb-reader
          ports:
            - containerPort: {{ .Values.mongodb.reader.httpPort }}
              protocol: TCP
          stdin: true
          tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
{{- end }}
