# Copyright (c) Mainflux
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-mongodb-writer-config
data:
  subjects.toml: |
    # If you want to listen on all subjects, just pass one element ["channels.>"], otherwise
    # pass the list of subjects (e.g ["channels.<channel_id>", "channels.<channel_id>.sub.topic.x", ...]).
    [subjects]
    filter = ["channels.>"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongodb-writer
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: mongodb-writer
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "{{ .Values.mongodb.writer.httpPort }}"
        prometheus.io/scrape: "true"
      labels:
        app: {{ .Release.Name }}
        component: mongodb-writer
    spec:
      containers:
        - env:
            - name: MG_MONGO_WRITER_LOG_LEVEL
              value: debug
            - name: MG_BROKER_URL
              value: nats://{{ .Release.Name }}-nats-client:{{ .Values.defaults.natsPort }}
            - name: MG_MONGO_WRITER_PORT
              value: "{{ .Values.mongodb.writer.httpPort }}"
            - name: MG_MONGO_WRITER_BATCH_SIZE
              value: "5000"
            - name: MG_MONGO_WRITER_BATCH_TIMEOUT
              value: "5"
            - name: MG_MONGO_WRITER_DB
              value: "{{ .Values.mongodb.database }}"
            - name: MG_MONGO_WRITER_DB_USER
              value: "{{ .Values.mongodb.adminUser.name }}"
            - name: MG_MONGO_WRITER_DB_PASS
              value: "{{ .Values.mongodb.adminUser.pwd }}"
            - name: MG_MONGO_WRITER_DB_HOST
              value: {{ .Release.Name }}-mongodb
            - name: MG_MONGO_WRITER_DB_PORT
              value: "{{ .Values.mongodb.dbPort }}"
            - name: MG_MONGO_WRITER_CONFIG_PATH
              value: "{{ .Values.mongodb.configPath }}"
            - name: MG_MONGO_WRITER_CONTENT_TYPE
              value: "{{ .Values.mongodb.contentType }}"
            - name: MG_MONGO_WRITER_TRANSFORMER
              value: "{{ .Values.mongodb.transformer }}"
            - name: MG_MONGO_WRITER_TRANSFORMER
              value: "{{ .Values.mongodb.transformer }}" 
          image: "{{ default .Values.defaults.image.repository .Values.mongodb.writer.image.repository }}/mongodb-writer:{{ default .Values.defaults.image.tag .Values.mongodb.writer.image.tag }}"
          imagePullPolicy: {{ default .Values.defaults.image.pullPolicy .Values.mongodb.writer.image.pullPolicy }}
          name: {{ .Release.Name }}-mongodb-writer
          ports:
            - containerPort: {{ .Values.mongodb.writer.httpPort }}
              protocol: TCP
          stdin: true
          tty: true
          volumeMounts:
            - mountPath: {{ .Values.mongodb.configPath }}
              name: mongodb-writer-config
              subPath: subjects.toml
      {{- with .Values.defaults.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - configMap:
            defaultMode: 256
            name: {{ .Release.Name }}-mongodb-writer-config
            optional: false
          name: mongodb-writer-config
{{- end }}
