# Copyright (c) Mainflux
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-things
spec:
  replicas: {{ .Values.defaults.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: things
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: things
    spec:
      containers:
        - env:
            - name: MF_JAEGER_URL
              value: {{ .Release.Name }}-jaeger-operator-jaeger-agent:{{ .Values.defaults.jaegerPort }}
            - name: MF_THINGS_AUTH_GRPC_PORT
              value: "{{ .Values.things.authGrpcPort }}"
            - name: MF_THINGS_AUTH_HTTP_PORT
              value: "{{ .Values.things.authHttpPort }}"
            - name: MF_THINGS_CACHE_URL
              value: {{ .Release.Name }}-redis-auth-master:{{ .Values.things.redisCachePort }}
            - name: MF_THINGS_DB
              value: {{ .Values.postgresqlthings.auth.database | quote }}
            - name: MF_THINGS_DB_HOST
            {{- if .Values.postgresqlthings.enabled }}
              value: {{ .Release.Name }}-postgresqlthings
            {{- else }}
              value: {{ .Values.postgresqlthings.postgresqlHost | quote}}
            {{- end }}
            - name: MF_THINGS_DB_PASS
              value: {{ .Values.postgresqlthings.auth.password | quote}}
            - name: MF_THINGS_DB_PORT
              value: "{{ .Values.things.dbPort }}"
            - name: MF_THINGS_DB_USER
              value: {{ .Values.postgresqlthings.auth.username | quote}}
            - name: MF_THINGS_ES_URL
              value: {{ .Release.Name }}-redis-streams-master:{{ .Values.things.redisESPort }}
            - name: MF_THINGS_HTTP_PORT
              value: "{{ .Values.things.httpPort }}"
            - name: MF_THINGS_LOG_LEVEL
              value: {{ default .Values.defaults.logLevel .Values.things.logLevel }}
            - name: MF_AUTH_GRPC_URL
              value: {{ .Release.Name }}-envoy:{{ .Values.auth.grpcPort }}
          image: "{{ default .Values.defaults.image.repository .Values.things.image.repository }}/things:{{ default .Values.defaults.image.tag .Values.things.image.tag }}"
          imagePullPolicy: {{ default .Values.defaults.image.pullPolicy .Values.things.image.pullPolicy }}
          name: {{ .Release.Name }}-things
          ports:
            - containerPort: {{ .Values.things.httpPort }}
              protocol: TCP
            - containerPort: {{ .Values.things.authGrpcPort }}
              protocol: TCP
            - containerPort: {{ .Values.things.authHttpPort }}
              protocol: TCP
      {{- with .Values.defaults.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
