# Copyright (c) Mainflux
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.twins.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-twins
spec:
  selector:
    app: {{ .Release.Name }}
    component: twins
  ports:
    - port: {{ .Values.twins.httpPort }
      protocol: TCP
{{- end }}
