# Copyright (c) Mainflux
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.twins.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-twins
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: twins
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: twins
    spec:
      containers:
        - env:
            - name: MF_TWINS_LOG_LEVEL
              value: {{ default .Values.defaults.logLevel .Values.twins.logLevel }}
            - name: MF_TWINS_HTTP_PORT
              value: "{{ .Values.twins.httpPort }"
            - name: MF_TWINS_DB
              value: mainflux-twins
            - name: MF_TWINS_DB_HOST
              value: {{ .Release.Name }}-twins-db
            - name: MF_TWINS_DB_PORT
              value: "{{.Values.twins.dbPort }}"
            - name: MF_TWINS_CHANNEL_ID
              value: {{.Values.twins.channelId }}
            - name: MF_NATS_URL
              value: nats://{{ .Release.Name }}-nats-client:{{ .Values.defaults.natsPort }}
            - name: MF_AUTHN_GRPC_URL
              value: {{ .Release.Name }}-envoy:{{ .Values.authn.grpcPort }
            - name: MF_TWINS_CACHE_URL
              value: {{ .Release.Name }}-redis-streams-master:{{ .Values.twins.redisCachePort }}
          image: "{{ default .Values.defaults.image.repository .Values.twins.image.repository }}/twins:{{ default .Values.defaults.image.tag .Values.twins.image.tag }}"
          imagePullPolicy: {{ default .Values.defaults.image.pullPolicy .Values.twins.image.pullPolicy }}
          name: {{ .Release.Name }}-twins
          ports:
            - containerPort: {{ .Values.twins.httpPort }
              protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
{{- end }}
