# Copyright (c) Mainflux
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ui
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: ui
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: ui
    spec:
      containers:
        - env:
            - name: MF_UI_PORT
              value: "{{ .Values.ui.port }}"
            - name: MF_UI_MQTT_WS_URL
              value: 'ws://localhost/mqtt'
            - name: MF_PROXY_AUTH
              value: "{{ .Values.ui.proxy }}"
            - name: MF_UI_APP_PREFIX
              value: "{{ .Values.ui.prefix }}"
            - name : MF_PROXY_LOGOUT_URL
              value: "{{ .Values.ui.logoutUrl }}"
          image: "{{ default .Values.defaults.image.repository .Values.ui.image.repository }}/ui:{{ default .Values.defaults.image.tag .Values.ui.image.tag }}"
          imagePullPolicy: {{ default .Values.defaults.image.pullPolicy .Values.ui.image.pullPolicy }}
          name: ui
          ports:
            - containerPort: {{ .Values.ui.port }}
              protocol: TCP
          stdin: true
          tty: true
        {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
        {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
