Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-users-config
data:
  email.tmpl: |
    To: {{`{{range $index, $v := .To}}{{if $index}},{{end}}{{$v}}{{end}}`}}
    From: {{`{{.From}}`}}
    Subject: {{`{{.Subject}}`}}
    {{`{{.Header}}`}}
    You have initiated password reset.
    Follow the link below to reset password.
    {{`{{.Content}}`}}
    {{`{{.Footer}}`}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-users
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: users
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "{{ .Values.users.httpPort }}"
        prometheus.io/scrape: "true"
      labels:
        app: {{ .Release.Name }}
        component: users
    spec:
      containers:
        - env:
            - name: MG_JAEGER_URL
              value: "http://{{ .Release.Name }}-jaeger-collector:{{ .Values.defaults.jaegerCollectorPort }}/api/traces"
            - name: MG_USERS_DB
              value: {{ index .Values  "postgresqlusers" "auth" "database" | quote }}
            - name: MG_USERS_DB_HOST
            {{- if .Values.postgresqlusers.enabled }}
              value: {{ .Release.Name }}-postgresqlusers
            {{- else }}
              value: {{ .Values.postgresqlusers.postgresqlHost | quote }}
            {{- end }}
            - name: MG_USERS_DB_PASS
              value: {{ index .Values  "postgresqlusers" "auth" "password" }}
            - name: MG_USERS_DB_PORT
              value: {{ .Values.postgresqlusers.postgresqlPort | quote }}
            - name: MG_USERS_DB_USER
              value: {{ index .Values "postgresqlusers" "auth" "username" }}
            - name: MG_USERS_HTTP_PORT
              value: "{{ .Values.users.httpPort }}"
            - name: MG_USERS_LOG_LEVEL
              value: {{ default .Values.defaults.logLevel .Values.users.logLevel }}
            - name: MG_USERS_GRPC_PORT
              value: "{{ .Values.users.grpcPort }}"
            - name: MG_TOKEN_RESET_ENDPOINT
              value: "#/auth/reset-password"
            - name: MG_USERS_ADMIN_EMAIL
              value: "{{ .Values.users.adminEmail }}"
            - name: MG_USERS_ADMIN_PASSWORD
              value: "{{ .Values.users.adminPassword }}"
          image: "{{ default .Values.defaults.image.repository .Values.users.image.repository }}/users:{{ default .Values.defaults.image.tag .Values.users.image.tag }}"
          imagePullPolicy: {{ default .Values.defaults.image.pullPolicy .Values.users.image.pullPolicy }}
          name: {{ .Release.Name }}-users
          ports:
            - containerPort: {{ .Values.users.httpPort }}
              protocol: TCP
          volumeMounts:
            - mountPath: /email.tmpl
              name: users-config
              subPath: email.tmpl
      {{- with .Values.defaults.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - configMap:
            defaultMode: 256
            name: {{ .Release.Name }}-users-config
            optional: false
          name: users-config
