# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: magistrala
description: Magistrala IoT Platform
icon: https://avatars1.githubusercontent.com/u/13207490
type: application
version: 1.0.4        # Incremented chart version if the chart is updated
appVersion: "0.12.2"  # Update application version if the app is updated
home: https://abstractmachines.fr/magistrala.html
sources:
  - https://hub.docker.com/u/magistrala
maintainers:
  - name: drasko
    email: draasko.draskovic@abstractmachines.fr
  - name: dusan
    email: dusan.borovcanin@abstractmachines.fr

dependencies:
  - name: nats
    version: "1.2.1"
    repository: "@nats"

  - name: jaeger
    version: "3.1.1"
    repository: "@jaegertracing"

  - name: postgresql
    version: "12.5.6"
    repository: "@bitnami"
    alias: postgresqlauth
    condition: postgresqlauth.enabled

  - name: postgresql
    version: "12.5.6"
    repository: "@bitnami"
    alias: postgresqlspicedb
    condition: postgresqlspicedb.enabled

  - name: postgresql
    version: "12.5.6"
    repository: "@bitnami"
    alias: postgresqlthings
    condition: postgresqlthings.enabled

  - name: postgresql
    version: "12.5.6"
    repository: "@bitnami"
    alias: postgresqlusers
    condition: postgresqlusers.enabled


  - name: postgresql
    version: "12.5.6"
    repository: "@bitnami"
    alias: postgresqlbootstrap
    condition: postgresqlbootstrap.enabled

  - name: postgresql
    version: "12.5.6"
    repository: "@bitnami"
    alias: postgresqlcerts
    condition: postgresqlcerts.enabled

  - name: postgresql
    version: "12.5.6"
    repository: "@bitnami"
    alias: postgresqlinvitations
    condition: postgresqlinvitations.enabled

  - name: postgresql
    version: "12.5.6"
    repository: "@bitnami"
    alias: postgresqljournal
    condition: postgresqljournal.enabled

  - name: postgresql
    version: "12.5.6"
    repository: "@bitnami"
    alias: timescaledb
    condition: timescaledb.enabled

  - name: postgresql
    version: "12.5.6"
    repository: "@bitnami"
    alias: postgresqlui
    condition: postgresqlui.enabled

  - name: redis
    version: "19.6.2"
    repository: "@bitnami"
    alias: redis-things

  - name: vault
    version: "0.28.1"
    repository: "@hashicorp"
    alias: "vault"
    condition: vault.enabled
