apiVersion: v1
entries:
  jaeger:
  - apiVersion: v2
    appVersion: 1.53.0
    created: "2024-09-09T12:47:29.618859922+03:00"
    dependencies:
    - condition: provisionDataStore.cassandra
      name: cassandra
      repository: https://charts.helm.sh/incubator
      version: 0.15.3
    - condition: provisionDataStore.elasticsearch
      name: elasticsearch
      repository: https://charts.bitnami.com/bitnami
      version: 20.0.4
    - condition: provisionDataStore.kafka
      name: kafka
      repository: https://charts.bitnami.com/bitnami
      version: 26.6.2
    - name: common
      repository: https://charts.bitnami.com/bitnami
      version: 2.x.x
    description: A Jaeger Helm chart for Kubernetes
    digest: cce55a81a90666043e6f60c998551dbc98c35781a4abb0a61d9442977d5be3fa
    home: https://jaegertracing.io
    icon: https://www.jaegertracing.io/img/jaeger-icon-reverse-color.svg
    keywords:
    - jaeger
    - opentracing
    - tracing
    - instrumentation
    kubeVersion: '>= 1.21-0'
    maintainers:
    - email: david.vonthenen@dell.com
      name: dvonthenen
    - email: ankit.mehta@appian.com
      name: mehta-ankit
    - email: michael.lorant@fairfaxmedia.com.au
      name: mikelorant
    - email: naseem@transit.app
      name: naseemkullah
    - email: me@pavelnikolov.net
      name: pavelnikolov
    - email: jkowall@kowall.net
      name: jkowall
    name: jaeger
    sources:
    - https://hub.docker.com/u/jaegertracing/
    type: application
    urls:
    - charts/jaeger-3.1.1.tgz
    version: 3.1.1
  magistrala:
  - apiVersion: v2
    appVersion: 0.12.1
    created: "2024-09-09T12:47:29.58940348+03:00"
    dependencies:
    - name: nats
      repository: '@nats'
      version: 1.2.1
    - name: jaeger
      repository: '@jaegertracing'
      version: 3.1.1
    - alias: postgresqlauth
      condition: postgresqlauth.enabled
      name: postgresql
      repository: '@bitnami'
      version: 12.5.6
    - alias: postgresqlspicedb
      condition: postgresqlspicedb.enabled
      name: postgresql
      repository: '@bitnami'
      version: 12.5.6
    - alias: postgresqlthings
      condition: postgresqlthings.enabled
      name: postgresql
      repository: '@bitnami'
      version: 12.5.6
    - alias: postgresqlusers
      condition: postgresqlusers.enabled
      name: postgresql
      repository: '@bitnami'
      version: 12.5.6
    - alias: postgresqlbootstrap
      condition: postgresqlbootstrap.enabled
      name: postgresql
      repository: '@bitnami'
      version: 12.5.6
    - alias: postgresqlcerts
      condition: postgresqlcerts.enabled
      name: postgresql
      repository: '@bitnami'
      version: 12.5.6
    - alias: postgresqlinvitations
      condition: postgresqlinvitations.enabled
      name: postgresql
      repository: '@bitnami'
      version: 12.5.6
    - alias: postgresqljournal
      condition: postgresqljournal.enabled
      name: postgresql
      repository: '@bitnami'
      version: 12.5.6
    - alias: timescaledb
      condition: timescaledb.enabled
      name: postgresql
      repository: '@bitnami'
      version: 12.5.6
    - alias: postgresqlui
      condition: postgresqlui.enabled
      name: postgresql
      repository: '@bitnami'
      version: 12.5.6
    - alias: redis-things
      name: redis
      repository: '@bitnami'
      version: 19.6.2
    - alias: vault
      condition: vault.enabled
      name: vault
      repository: '@hashicorp'
      version: 0.28.1
    description: Magistrala IoT Platform
    digest: e44c5d9ee747bc21108dab6e4ec8b5e589259aea6b4472a5b0f0f6b7e51aec73
    home: https://abstractmachines.fr/magistrala.html
    icon: https://avatars1.githubusercontent.com/u/13207490
    maintainers:
    - email: draasko.draskovic@abstractmachines.fr
      name: drasko
    - email: dusan.borovcanin@abstractmachines.fr
      name: dusan
    name: magistrala
    sources:
    - https://hub.docker.com/u/magistrala
    type: application
    urls:
    - magistrala-1.0.3.tgz
    version: 1.0.3
  nats:
  - apiVersion: v2
    appVersion: 2.10.17
    created: "2024-09-09T12:47:29.621275836+03:00"
    description: A Helm chart for the NATS.io High Speed Cloud Native Distributed
      Communications Technology.
    digest: b35d6fba525e98dc0b0f060929b600bb60ce699a34623682a82c9fb449e14a2c
    home: http://github.com/nats-io/k8s
    icon: https://nats.io/img/nats-icon-color.png
    keywords:
    - nats
    - messaging
    - cncf
    maintainers:
    - email: info@nats.io
      name: The NATS Authors
      url: https://github.com/nats-io
    name: nats
    urls:
    - charts/nats-1.2.1.tgz
    version: 1.2.1
  postgresql:
  - annotations:
      category: Database
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 15.3.0
    created: "2024-09-09T12:47:29.625601496+03:00"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: PostgreSQL (Postgres) is an open source object-relational database
      known for reliability and data integrity. ACID-compliant, it supports foreign
      keys, joins, views, triggers and stored procedures.
    digest: 85536e44a499d7e7a3c35d176c57b7116d8659e86ff6b49b9171d0b77dc94c84
    home: https://bitnami.com
    icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-220x234.png
    keywords:
    - postgresql
    - postgres
    - database
    - sql
    - replication
    - cluster
    maintainers:
    - name: VMware, Inc.
      url: https://github.com/bitnami/charts
    name: postgresql
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/postgresql
    urls:
    - charts/postgresql-12.5.6.tgz
    version: 12.5.6
  redis:
  - annotations:
      category: Database
      images: |
        - name: kubectl
          image: docker.io/bitnami/kubectl:1.30.2-debian-12-r2
        - name: os-shell
          image: docker.io/bitnami/os-shell:12-debian-12-r24
        - name: redis
          image: docker.io/bitnami/redis:7.2.5-debian-12-r2
        - name: redis-exporter
          image: docker.io/bitnami/redis-exporter:1.61.0-debian-12-r2
        - name: redis-sentinel
          image: docker.io/bitnami/redis-sentinel:7.2.5-debian-12-r2
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 7.2.5
    created: "2024-09-09T12:47:29.633168733+03:00"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: Redis(R) is an open source, advanced key-value store. It is often
      referred to as a data structure server since keys can contain strings, hashes,
      lists, sets and sorted sets.
    digest: 4389f91f8ddabe85b0b2b2d38492bb3c07ba8dec93498c0e5ddc7ca675aa6571
    home: https://bitnami.com
    icon: https://bitnami.com/assets/stacks/redis/img/redis-stack-220x234.png
    keywords:
    - redis
    - keyvalue
    - database
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: redis
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/redis
    urls:
    - charts/redis-19.6.2.tgz
    version: 19.6.2
  vault:
  - annotations:
      charts.openshift.io/name: HashiCorp Vault
    apiVersion: v2
    appVersion: 1.17.2
    created: "2024-09-09T12:47:29.637888631+03:00"
    description: Official HashiCorp Vault Chart
    digest: 99efe00f5527182e76d6e7a0ccf9d4797badd248cb8fe070fbe117e0b6cb58d7
    home: https://www.vaultproject.io
    icon: https://github.com/hashicorp/vault/raw/f22d202cde2018f9455dec755118a9b84586e082/Vault_PrimaryLogo_Black.png
    keywords:
    - vault
    - security
    - encryption
    - secrets
    - management
    - automation
    - infrastructure
    kubeVersion: '>= 1.20.0-0'
    name: vault
    sources:
    - https://github.com/hashicorp/vault
    - https://github.com/hashicorp/vault-helm
    - https://github.com/hashicorp/vault-k8s
    - https://github.com/hashicorp/vault-csi-provider
    urls:
    - charts/vault-0.28.1.tgz
    version: 0.28.1
generated: "2024-09-09T12:47:29.536259877+03:00"
