name: Update Chart Metadata

on: push

jobs:  
  update-chart-metadata:    
    runs-on: ubuntu-latest    
    steps:      
      - uses: actions/checkout@v4      
      - uses: gabe565/setup-helm-docs-action@v1.0.4      
      - run: helm-docs